spring:
  application:
    name: sb-provider
server:
  host: localhost
  port: 7022

eureka:
  client:
    #将此项目注册到Eureka服务
    register-with-eureka: true
    service-url:
      defaultZone: http://root:root@localhost:7001/eureka
