spring:
  application:
    name: command
server:
  port: 8090

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka
  instance:
      prefer-ip-address: true
#hystrix的超时时间
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 1000 #1000毫秒

feign.hystrix.enabled: true